---
# Config of KygekJoinUI plugin
# KygekJoinUI plugin by Kygekraqmak, aminozomty, and KygekTeam
# If your config.yml data is lost it may be in config_old.yml


# Use "{line}" to make a new line
# Use "&" as formatting codes for texts
# Use "{player}" to display the player's name
# Use "{online}" to display the current players on the server
# Use "{max_online}" to display the server's maximum players
# Use "{world}" to display the world the KygekJoinUI shows on


# How to set up:
# command-mode: console             = Change the command execute mode (as player or console)
# join-first-time: false            = Whether to only show KygekJoinUI to players that joined the server for the first time
# commands-on-close:                = Commands that will be executed when player close the form (X button at top right corner)
# - say Hello!                      = You can add as many as you want
# Mode: SimpleForm                  = Change the KygekJoinUI mode (SimpleForm or ModalForm)
# title: KygekJoinUI                = Change the title of KygekJoinUI
# content: Change in config.yml!    = Change the content of KygekJoinUI
# Buttons:                          = The button(s) of KygekJoinUI (SimpleForm or ModalForm)
#   SimpleForm:                     = Button(s) that will show if you choose SimpleForm mode
#   - name: "Ok"                    = Change the button of SimpleForm mode of KygekJoinUI
#     image: "textures/ui/confirm"  = [Optional] Add an image that will be shown beside the button
#                                     IMPORTANT: Please visit https://github.com/KygekDev/KygekDev/blob/master/docs/using-images-kygekdev-plugins.md for image guides
#     commands:                     = [Optional] Commands that will be executed when the button is pressed
#     - "say Hello!"                = You can add as many commands you want
#   ModalForm:                      = Button(s) that will show if you choose ModalForm mode (only supports 2 buttons!)
#     B1:                           = First button of ModalForm mode (Don't change!)
#       name: Button1               = Change the button of the first ModalForm button
#       command: say Button1!       = Change the command that will be executed when the first button is pressed
#     B2:                           = Second button of ModalForm mode (Don't change!)
#       name: Button2               = Change the button of the second ModalForm button
#       command: say Button2!       = Change the command that will be executed when the second button is pressed


# Set the plugin here!
command-mode: console
join-first-time: false
commands-on-close:
- say Hello!
Mode: SimpleForm
title: KygekJoinUI
content: Change in config.yml!
Buttons:
  SimpleForm:
  - name: "Ok"
    image: "textures/ui/confirm"
    commands:
    - "say Hello!"
  ModalForm:
    B1:
      name: Button1
      command: say Button1!
    B2:
      name: Button2
      command: say Button2!


# Whether to check for plugin updates (Recommended)
check-updates: true

# Whether to warn if plugin is running on a development version (Recommended)
warn-development: true


##### DANGER ZONE #####
# Do not change this (Only for internal use)!
config-version: "2.1"
#######################
...
